version: '3.4'

networks:
  back-tier:
    driver: bridge

services:
  webapp:
    image: webapp:latest
    build:
      context: ./Diplom-2023
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "7198:80"
    depends_on:
      - db
    networks:
      - back-tier

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - back-tier
  
  angular-app:
    image: angular-app:latest
    build:
      context: ./ResQueAngularApp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - back-tier

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - webapp
      - angular-app
    networks:
      - back-tier
